global:
  scrape_interval:     30s # メトリクスを収集する間隔を設定 (デフォルトは 1 分ごと)

scrape_configs:
  - job_name: telegraf # この収集ジョブの名前を "telegraf" と定義
    static_configs:
      - targets:
        - telegraf:9091 # ホスト名 "telegraf" の 9091 ポートを監視対象
